---
provider:
  host: "{{ ansible_host }}"
  username: john
  password: "{{ vault_provider_password }}"
  authorize: yes
  
loopback:
  - name: "Loopback0"
    description: "{{ lo0.description }}"
    ip: "{{ lo0.ip }}"
    mask: 255.255.255.240
  
