---
- name: IOS | Set Hostname
  ios_config:
    provider: "{{ provider }}"
    lines: hostname "{{ inventory_hostname }}"
    
- name: IOS | Configure Loopback Interfaces
  ios_config:
    provider: "{{ provider }}" # Read from group_vars/all.yml
    lines:
    - description: "{{ item.description }}"
    - ip address: "{{ item.ip }} {{item.mask}}"
    parents: "interface {{ item.name }}"
  with_items: "{{ loopback }}" # Should be read from group_vars/router.yml
  tags: loopback
    
